config/routes.rb
Rails.application.routes.draw do
  get '/soundcloud/connect',    :to => 'soundcloud#connect'
  get 'soundcloud/oauth-callback', to: 'soundcloud#connected'
  get 'logout', to: 'soundcloud#destroy', as: 'logout'
  
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root          'pages#home'
  get 'help' => 'pages#help'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :edit, :create, :update]
  resources :listings

end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :listings, dependent: :destroy
    attr_accessor :remember_token, :activation_token, :reset_token
    before_save :downcase_email
    before_create :create_activation_digest
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true 
    
      # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
    
  #returns a random token
    def User.new_token
        SecureRandom.urlsafe_base64
    end
    
    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end
    
    # Returns true if the given token matches the digest.
    def authenticated?(remember_token)
        return false if remember_digest.nil?
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end
    
    #Forgets a user
    def forget
        update_attribute(:remember_digest, nil)
    end
    
      # Returns true if the given token matches the digest.
    def authenticated?(attribute, token)
        digest = send("#{attribute}_digest")
        return false if digest.nil?
        BCrypt::Password.new(digest).is_password?(token)
    end
    
      # Activates an account.
    def activate
        update_attribute(:activated,    true)
        update_attribute(:activated_at, Time.zone.now)
    end
    

  # Sends activation email.
    def send_activation_email
        UserMailer.account_activation(self).deliver_now
    end
    
      # Sets the password reset attributes.
    def create_reset_digest
        self.reset_token = User.new_token
        update_attribute(:reset_digest,  User.digest(reset_token))
        update_attribute(:reset_sent_at, Time.zone.now)
    end

  # Sends password reset email.
    def send_password_reset_email
        UserMailer.password_reset(self).deliver_now
    end
    
      # Returns true if a password reset has expired.
    def password_reset_expired?
        reset_sent_at < 2.hours.ago
    end
    

    
    private
        #converts email to lower-case
        def downcase_email
            self.email = email.downcase
        end
    
        def create_activation_digest
            self.activation_token = User.new_token
            self.activation_digest = User.digest(activation_token)
        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :logged_in_user, only: [:edit, :update, :destroy]
    before_action :correct_user, only: [:edit, :update]
    before_action :admin_user, only: [:index, :destroy]
  
  def index
        @users = User.paginate(page: params[:page])  
  end
    
  def show
     @user = User.find(params[:id])
     @listings = @user.listings.all
     @soundcloudid = @user.soundcloud_user_id
  end

    
  def new
      @user = User.new
  end
    
  def create
     @user = User.new(user_params)
      if @user.save
#        uncomment if email account activation is needed  
#        @user.send_activation_email
#        flash[:info] = "Please check your email to activate your account."  
        log_in @user
        flash[:success] = "Welcome to BandMates"
        redirect_to @user
      else
          render 'new'
      end
  end
    
  def edit
  end
    
  def update
     if @user.update_attributes(user_params)
        flash[:success] = "Profile updated"
        redirect_to @user
     else
        render 'edit' 
     end
  end
    
  def destroy
     User.find(params[:id]).destroy
     flash[:success] = "User destroyed"
     redirect_to users_url
  end
    
    private
    
        def user_params
            params.require(:user).permit(:name, :email, :password, :password_confirmation, :soundcloud_user_id,:soundcloud_access_token)
        end
    
        def correct_user
            @user = User.find(params[:id])
            redirect_to(root_url) unless current_user?(@user)
        end
    
        def admin_user
            redirect_to(root_url) unless current_user.admin?
        end
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
    
    
end

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'Update') %>     
<div class="container">
    	<div class="row">
			<div class="col-md-6 col-md-offset-3">
				<div class="panel panel-signup">
					<div class="panel-heading">
						<div class="row">
                            <div class="col-xs-12">
								<a href="#" class="active" id="register-form-link"><h1>Update User Information</h1></a>
							</div>
						</div>
						<hr>
					</div>
					<div class="panel-body">
						<div class="row">
							<div class="col-lg-12">

                                    <%= form_for(@user) do |f| %>
                                <%= render 'shared/error_messages', object: f.object %>
									<div class="form-group">
                                        <%= f.text_field :name, class: 'form-control', placeholder:"Name" %>
									</div>
                                    
									<div class="form-group">
                                        <%= f.email_field :email, class: 'form-control', placeholder:"Email Address" %>
									</div>
                                    
									<div class="form-group">
                                        <%= f.password_field :password, class: 'form-control', placeholder:"Password" %>
									</div>
									<div class="form-group">
<%= f.password_field :password_confirmation, class: 'form-control', placeholder:"Confirm Password" %>						
									</div>
									<div class="form-group">
										<div class="row">
											<div class="col-sm-6 col-sm-offset-3">
                                                <%= f.submit "Save changes", class:"form-control btn btn-register" %>
                                                
                                        
											</div>
       										</div><br>
                                    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">change</a>
    </div>
									</div>     

                                    <% end %>
								    

							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
    <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<!--SIGNUP START-->
<div class="container">
    	<div class="row">
			<div class="col-md-6 col-md-offset-3">
				<div class="panel panel-signup">
					<div class="panel-heading">
						<div class="row">
                            <div class="col-xs-12">
								<a href="#" class="active" id="register-form-link"><h1>Sign up</h1></a>
							</div>
						</div>
						<hr>
					</div>
					<div class="panel-body">
						<div class="row">
							<div class="col-lg-12">

                                    <%= form_for(@user) do |f| %>
                                <%= render 'shared/error_messages' %>
									<div class="form-group">
                                        <%= f.text_field :name, class: 'form-control', placeholder:"Name"%>
									</div>
                                    
									<div class="form-group">
                                        <%= f.email_field :email, class: 'form-control', placeholder:"Email Address" %>
									</div>
                                    
									<div class="form-group">
                                        <%= f.password_field :password, class: 'form-control', placeholder:"Password" %>
									</div>
									<div class="form-group">
<%= f.password_field :password_confirmation, class: 'form-control', placeholder:"Confirm Password" %>						
									</div>
									<div class="form-group">
										<div class="row">
											<div class="col-sm-6 col-sm-offset-3">
                                                <%= f.submit "Sign up", class:"form-control btn btn-register" %>
											</div>
       										</div>
									</div>                                     									<div class="form-group">
										<div class="row">
											<div class="col-lg-12">
												<div class="text-center">
				<p>Already a user? <%= link_to "Login here!", "#" %></p>					
												</div>
											</div>
										</div>
									</div>

                                    <% end %>
                                
								

							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
    <h1>
      <%= gravatar_for @user %>
      <%= @user.name %>
    </h1>
    <% if @soundcloudid.present? %>
    <% else %>
        <%= link_to image_tag("soundcloud_connect.png"), soundcloud_connect_path %>
    <% end %>
<div class="row">
    <h1>Listings(<%= @user.listings.count %>)
    <%= link_to "New listing", new_listing_path, class: "btn btn-primary" %>
    </h1>
</div>
<div class="container">
    <div class="row">
            <% @user.listings.each do |l| %>
                <li><%= l.description %>
              <%= link_to "Edit", edit_listing_path(l) %> |
              <%= link_to "Delete", l, method: :delete,
                                              data: { confirm: "You sure?" } %>
                </li>
            <% end %>
    </div>
</div>