config/routes.rb
Rails.application.routes.draw do
  get '/soundcloud/connect',    :to => 'soundcloud#connect'
  get 'soundcloud/oauth-callback', to: 'soundcloud#connected'
  get 'logout', to: 'soundcloud#destroy', as: 'logout'
  
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root          'pages#home'
  get 'help' => 'pages#help'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :edit, :create, :update]
  resources :listings

end

app/views/layouts/_header.html.erb
<!-- Menu -->
	<nav class="menu" id="theMenu">
		<div class="menu-wrap">
			<h1 class="logo"><%= link_to "BandMates", root_path %></h1>
			<i class="icon-remove menu-close"></i>
            <% if logged_in? %>
                <%= link_to "Home", root_path %>
                <%= link_to "Find BandMates", listings_path %>
                <%= link_to "Profile", current_user %>
            <% if current_user.admin? %>
                <%= link_to "Users", users_path %>
            <% end %>
                <%= link_to "Settings", edit_user_path(current_user) %>
                <%= link_to "Help", help_path %>
                <%= link_to "Log out", logout_path, method: "delete" %>
            <% else %>
                <%= link_to "Home", root_path %>
                <%= link_to "Help", help_path %>
                <%= link_to "Log in", login_path %>
                <%= link_to "Sign up", signup_path %>
            <% end %>
		</div>
		
		<!-- Menu button -->
        
		<div id="menuToggle"></div>
<!--        <i class="fa fa-bars fa-2x fa-inverse"></i>-->
	</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="mobile-web-app-capable" content="yes">
<!--    <script src="https://connect.soundcloud.com/sdk/sdk-3.0.0.js"></script>-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
        
</head>
<body class='<%= controller_name %> <%= action_name %>' data-target="#theMenu" data-role="page">
    <%= render 'layouts/header' %>
    <div class="container">
        <% flash.each do |message_type, message| %>
            <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
      <%= yield %>
    </div>
  </body>
</html>